# Generated by Django 2.0.1 on 2018-01-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
