# Generated by Django 2.0.1 on 2018-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_content', '0002_auto_20180124_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=3000),
        ),
    ]
