# Generated by Django 2.0.1 on 2018-02-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_content', '0003_auto_20180124_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
