# Generated by Django 2.0.1 on 2018-02-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_content', '0004_remove_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=100)),
                ('created_date', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
    ]
