# Generated by Django 2.0.1 on 2018-03-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_content', '0007_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.TextField(max_length=10)),
                ('class_no', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='month',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('DISCARDED', 'Discarded'), ('OUTDATED', 'Outdated'), ('USED', 'Used'), ('DELETED', 'Deleted')], default='ACCEPTED', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_content.Course'),
        ),
    ]
