# Generated by Django 2.0.1 on 2018-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_content', '0008_auto_20180311_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='month',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
    ]
