# Generated by Django 2.0.1 on 2018-04-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_content', '0012_auto_20180407_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_name', models.CharField(max_length=20)),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_content.UserGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='logtable',
            name='operation',
            field=models.CharField(max_length=20),
        ),
    ]
