# Generated by Django 2.0.1 on 2018-04-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_content', '0013_auto_20180407_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_content.Chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='medium',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
